- name: 'Install nginx server'
  hosts: server1
  become: yes
  tasks:
    - name: 'Update server1'
      dnf:
        name: '*'
        state: latest

    - name: 'Install Nginx'
      dnf:
        name: nginx
        state: latest

    - name: 'Run Nginx'
      service:
        name: nginx
        state: started
        enabled: yes

